name: conduit

services:
  frontend:
    build:
      context: ./conduit-frontend
      args: 
        - API_URL=${API_URL}
    restart: unless-stopped
    ports: 
      - "8282:80"

  backend:
    build:
      context: ./conduit-backend
    restart: unless-stopped
    ports: 
      - "8283:80"
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST}
      DEBUG: ${DEBUG}
    depends_on:
      - db

  db:
    image: postgres:18.4-alpine3.24
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8285:8080

volumes:
  db: